name: PashaSatei

options:
  bundleIdPrefix: com.shu39a
  deploymentTarget:
    iOS: "16.0"

settings:
  base:
    SWIFT_VERSION: 5.0
    CURRENT_PROJECT_VERSION: 6
    MARKETING_VERSION: 0.1

targets:
  PashaSatei:
    type: application
    platform: iOS
    deploymentTarget: "16.0"

    sources:
      - path: Sources/PashaSatei
      - path: Resources/Assets.xcassets

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shu39a.pashasatei
        PRODUCT_NAME: PashaSatei
        INFOPLIST_FILE: Sources/PashaSatei/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: NO

    scheme:
      testTargets: []
